series: Basic C++
title: Casting
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: A look at type conversions for basic data types.
language: C++
tags:
  - Core
extra_resources:
  - link: http://www.cplusplus.com/doc/tutorial/typecasting/
    title: An article about the different kinds of typecasting.
connections:
  - series: Basic C++
    title: Data Types